### ISSUE TITLE
Release Cosmos 1.6.0

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-cosmos#1103]
* [x] https://github.com/astronomer/astronomer-cosmos/issues/1090
* [x] https://github.com/astronomer/astronomer-cosmos/issues/1087
* [x] https://github.com/astronomer/astronomer-cosmos/issues/1085
* [x] https://github.com/astronomer/astronomer-cosmos/issues/1076
* [x] https://github.com/astronomer/astronomer-cosmos/issues/1072
* [x] https://github.com/astronomer/astronomer-cosmos/issues/1042)
* [x] https://github.com/astronomer/astronomer-cosmos/issues/953
* [x] https://github.com/astronomer/astronomer-cosmos/issues/943 
* [x] https://github.com/astronomer/astronomer-cosmos/issues/930 
* [x] https://github.com/astronomer/astronomer-cosmos/issues/906 
* [x] https://github.com/astronomer/astronomer-cosmos/issues/875 
* [x] https://github.com/astronomer/astronomer-cosmos/issues/823 
* [x] https://github.com/astronomer/astronomer-cosmos/issues/693 
* [x] https://github.com/astronomer/astronomer-cosmos/issues/630 
* [x] https://github.com/astronomer/astronomer-cosmos/issues/610
* [x] https://github.com/astronomer/astronomer-cosmos/issues/572
* [x] https://github.com/astronomer/astronomer-cosmos/issues/535
* [x] https://github.com/astronomer/astronomer-cosmos/issues/448

**Comment by tatiana** [comment]
I updated the description of this release, to contain all the scope.

This is the list of tasks:
* https://github.com/astronomer/astronomer-cosmos/issues/958
* https://github.com/astronomer/astronomer-cosmos/issues/1042
* https://github.com/astronomer/astronomer-cosmos/issues/927
* https://github.com/astronomer/astronomer-cosmos/issues/894
* https://github.com/astronomer/astronomer-cosmos/issues/1078
* https://github.com/astronomer/astronomer-cosmos/issues/1075
* https://github.com/astronomer/astronomer-cosmos/issues/1072
* https://github.com/astronomer/astronomer-cosmos/issues/448
* https://github.com/astronomer/astronomer-cosmos/pull/661
* https://github.com/astronomer/astronomer-cosmos/issues/875
* https://github.com/astronomer/astronomer-cosmos/issues/572
* https://github.com/astronomer/astronomer-cosmos/issues/630
* https://github.com/astronomer/astronomer-cosmos/issues/535
* https://github.com/astronomer/astronomer-cosmos/issues/892
* https://github.com/astronomer/astronomer-cosmos/issues/959
* https://github.com/astronomer/astronomer-cosmos/issues/930

**Comment by phanikumv** [comment]
Can we check the scope again for 1.6.0 please? Are we on track to complete the above tasks

cc @tatiana

**Comment by pankajkoti** [comment]
We created an [alpha7](https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.6.0a7) last Friday with all the PRs merged as reflected in the updated issue description.

We're testing the alpha7 at the moment. 

We likely would have to release another alpha8 including the PR #1162 and test that together with other changes before releasing 1.6.0

**Comment by pankajkoti** [comment]
We've released Cosmos 1.6.0 via https://github.com/astronomer/astronomer-cosmos/pull/1080.

@phanikumv should we close this issue (labelled as epic) or keep it open?

**Comment by phanikumv** [comment]
@pankajkoti We can close this issue, great work on delivering the release 🎉
