### ISSUE TITLE
Cache `profiles.yml` file when using Cosmos `ProfileMapping`

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#925]
**Context**

In Cosmos 1.3, when users opt to use `ProfileMapping` Cosmos creates a `profiles.yml` file in potentially two places: 
* When using dbt ls to render the dbt project into an Airflow DAG
* When running dbt commands

Once we implement #924, which makes sure the profile file is created in the same way, we can extend the caching mechanism introduced in #904 also to cache the `profiles.yml` file.

Depends on: #924

**Acceptance criteria**

* [ ] Create a cache for the (if used, mocked and) non-mocked `profiles.yml` per DAG/TaskGroup when using `ProfileMapping`
* [ ] Decide on a criterion to decide when to use or not the cached `profiles.yml` (perhaps we could create a hash based on the keys in the connection and the profile args passed by the user?)
* [ ] Reuse the existing `profiles.yml` whenever possible without recreating it.
* [ ] The logs should contain less of the following:
```
Creating temporary profiles.yml at /var/folders/td/522y78v91d1f5wgh67mj3p0m0000gn/T/tmprpp66fdh/profiles.yml with the following contents:
default:
    outputs:
        dev:
            dbname: postgres
            host: 0.0.0.0
            password: '{{ env_var(''COSMOS_CONN_POSTGRES_PASSWORD'') }}'
            port: 5432
            schema: public
            type: postgres
            user: postgres
    target: dev
```

**Comment by tatiana** [comment]
A key part to remember in this ticket is that we'll likely need two caches per ProfileMapping instance:
- one when it's mocked
- another when it's not mocked

**Comment by tatiana** [comment]
Hi @pankajastro , following what we discussed, this PRs may help out:
