### ISSUE TITLE
Refactor Cosmos Airflow-based configuration to use settings.py

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#928]
**Context**

PR #904 introduced `settings.py` so developers/users can evaluate which values are being retrieved from Airflow configurations (either via `airflow.cfg` or environment variables).

This ticket aims to move other Cosmos-Airlfow configurations to be declared in this same `settings.py` file.

**Acceptance criteria**

* [ ] Identify parts of the code that use `airflow.configuration.conf`
* [ ] Centralise their definitions in the `settings.py` file
* [ ] Create a documentation page where we centralise and explain these, within Cosmos `/docs`
